#!/bin/bash

# Get data from .env file
source .env




# Install if not already
if [ $IP == 127.0.0.1 ]; then

	bash install
	exit

fi




# Open that IP slot
ifconfig lo0 alias $IP up
echo -e "'${IP}' is now available to build server ... ${GREEN}done${RESET}"




# Start the docker containers
echo "Starting the server..."
docker-compose up -d




# If Gulp file and package.json exist in theme folder
if [ -f wp-content/themes/${SLUG}/gulpfile.js ] && [ -f wp-content/themes/${SLUG}/package.json ]; then


	# RUN THE GULP
	echo "GULP is running..."
	docker-compose run --no-deps --rm gulp bash -c "npm start"


fi