#!/bin/bash

# Get data from .env file
source .env




# Install if not already
if [ $IP==127.0.0.1 ]; then

	bash install
	exit

fi




# Start the docker containers
echo "Starting the server..."
docker-compose up -d




# RUN THE GULP
echo "GULP is running..."
docker-compose run --no-deps --rm nodejs bash -c "npm start"