#!/bin/bash
source global.sh




# Install if not already
if [[ ! -f .env ]]; then

	echo "This project not installed yet."
	exit

fi


# Get data from .env file
source .env




# Builder updates
self_update




# Delete the server
echo "Server is closing..."
docker-compose down




# Revert the IP on environment file (.env)
sed -i "" "s/IP=${IP}/IP=127.0.0.1/g" .env;
echo -e "'${IP}' reverted on .env file ... ${GREEN}done${RESET}"




# Remove the host to the list
sudo bash config/etc-hosts.sh -remove $DOMAIN
killall -HUP mDNSResponder

echo -e "${GREEN}Project Uninstalled${RESET}"